nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://0310-105-73-97-232.ngrok-free.app']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['https://0310-105-73-97-232.ngrok-free.app']
